### ISSUE TITLE
I18n in embedded form

### ISSUE THREAD

**Issue by jmzlx** [propelorm/sfPropelORMPlugin#146]
Hi,

I am working with Symfony 1.4 and Propel 1.6. I am trying to add i18n translations in an embedded form in the admin generator. However, when I try to save multiple new instances  of the embedded form at once, only one of the embedded forms gets a translation (from another embedded form, it's not the correct one), and the rest are blank. This is my schema.yml file (the symfony_i18n behaviour is set by default in propel.ini):

```
  products:
    _attributes: { phpName: Products }
    id: { phpName: Id, type: BIGINT, size: '20', primaryKey: true, autoIncrement: false, required: true }   
    photo: { phpName: Photo, type: LONGVARCHAR, required: false }
    _indexes: { brands_id: [brands_id], subcategories_id: [subcategories_id], categories_id: [categories_id] }
    _propel_behaviors:
      timestampable: ~
    _uniques: { code: [code] }

  products_i18n:
    _attributes: { phpName: ProductsI18n }
    description: { phpName: Description, type: LONGVARCHAR, required: false }

  dimensions:
    _attributes: { phpName: Dimensions }
    id: { phpName: Id, type: BIGINT, size: '20', primaryKey: true, autoIncrement: true, required: true }
    products_id: { phpName: ProductsId, type: BIGINT, size: '20', required: true, foreignTable: products, foreignReference: id, onDelete: CASCADE, onUpdate: CASCADE }
    value: { phpName: Value, type: VARCHAR, required: false }
    _propel_behaviors:
      i18n: { locale_alias: culture, locale_column: culture, i18n_table: dimensions_i18n, i18n_phpname: DimensionsI18n, i18n_columns: "title" }

  dimensions_i18n:
    _attributes: { phpName: DimensionsI18n }
    id: { type: BIGINT, size: '20', required: true, primaryKey: true, foreignTable: dimensions, foreignReference: id, onDelete: CASCADE, onUpdate: CASCADE }
    title: { phpName: Title, type: VARCHAR, required: false }
```

The Dimensions form is embedded using:

```
$this->embedRelation('Dimensions', array('add_delete' => true, 'title' => $i18n->__('Dimensions')));
```

And the translations are simply embedded using:

```
$this->embedI18n(array('en', 'ru'));
```

I have unsuccessfully tried to find the error. The most that I could find is that apparently, all of the DimensionsI18n objects are assigned to the same Dimension object, although there are two embedded DimensionsForm in the ProductsForm. This causes the values from the first DimensionsI18nForm to be overwriten by the second Dimensions18nForm for each culture. If you need more information, please let me know and I will be glad to provide it.
