### ISSUE TITLE
connection pooling parameter broken

### ISSUE THREAD

**Issue by brunnels** [propelorm/sfPropelORMPlugin#34]
Found this really old symfony ticket while researching a problem I was having with connection pooling. The problem still remains.  http://trac.symfony-project.org/ticket/6040

When defining two databases in my database.yml the last database defined determines the setting of propels connection pooling.
Example database.yml:

```
all:
  propel:
    class: sfPropelDatabase 
    param:
      dsn: mysql:dbname=test;host=localhost 
      username: test 
      password: test 
      encoding: utf8 
      persistent: true 
      pooling: true 
      classname: PropelPDO

  test2:
    class: sfPropelDatabase 
    param:
      dsn: mysql:dbname=test2;host=localhost 
      username: test 
      password: test 
      encoding: utf8
      persistent: true
      pooling: FALSE
      classname: PropelPDO
```

so I now have defined two database connections, first propel connected to test, pooling true then test2 connected to test2, pooling false

line 66 in symfony/lib/plugins/sfPropelPlugin/lib/database/sfPropelDatabase.class.php checks the state of pooling everytime:

```
if ($this->getParameter('pooling', false))
```

and modifies the value of the singleton

```
Propel::disableInstancePooling();
```

overriding the value of the base connection...
