### ISSUE TITLE
insert-sql task doesn't insert foreign key constraints when using PostgreSQL with multiple schema files and packages

### ISSUE THREAD

**Issue by enr-beck** [propelorm/sfPropelORMPlugin#41]
We discovered a problem when using relations between postgresql tables of different packages in multiple schema files. We're using propel 1.6, php 5.3.2 and postgresql 8.4.7

The SQL files are generated correctly and can be inserted into database by hand without errors. But when using the propel insert-sql task the constraints are not created in database (in our example the relation between tables "ls_image" and "ls_vendor_image").

Below you find 2 example schema files:

001_media_schema.yml

``` yaml
propel:
    ls_image:
        _attributes:  { phpName: lsImage, package: lib.model.media }
        id:
        filename:     { type: varchar, size: 255, required: true, index: unique }
        description:  { type: varchar, size: 5000 }
        author:       { type: varchar, size: 255 }
        created_at:
        updated_at:
```

002_vendor_schema.yml

``` yaml
propel:
    ls_vendor:
        _attributes:        { phpName: lsVendor, package: lib.model.vendor }
        id:                 { type: bigint, primaryKey: true, required: true, autoIncrement: true }
        name:               { type: varchar, size: 255, required: true }
        is_active:          { type: boolean, default: true, required: true }

    ls_vendor_image:
        _attributes:        { phpName: lsVendorImage, package: lib.model.vendor }
        id:
        vendor_id:          { type: bigint, required: true, foreignTable: ls_vendor, foreignReference: id, onDelete: cascade }
        image_id:           { type: integer, required: true, foreignTable: ls_image, foreignReference: id, onDelete: cascade }
        name:               { type: varchar, size: 255, required: true }
```
